### PR TITLE
Fix har

### LINKED ISSUE #7: npm install doesn't work
The har version in the `package-lock.json` file was causing problems while running `npm install`.

### PR DESCRIPTION
**Pull request by yoogottamk**
Fixes #7

### CODE REVIEW

**Comment by zubairabid** [comment]
@gaurangtandon can you try `npm install` with this branch? If it works we'll go ahead with it.

**Comment by GaurangTandon** [comment]
K I'll try

**Comment by GaurangTandon** [comment]
This branch is on Yoogottam's fork. Do I have to clone Yoogottam's repo first before being able to test?

**Comment by zubairabid** [comment]
@GaurangTandon Yes.

Also in the future @yoogottamk can you make branches on this repo itself? Saves the hassle

**Comment by GaurangTandon** [comment]
Can @YoogottamK please make a branch on this repo? I don't want to clone another repo :P EDIT: I'll clone anyway.

**Comment by GaurangTandon** [comment]
`npm install` now works without trouble. Meanwhile, I stumbled upon this issue also: (this is just after running `npm install`)

image

Best to clean that up too. How to fix it too?

**Comment by zubairabid** [comment]
Yeah saw that. Try the `npm audit fix` they suggest. It's probably fixed by updating the package.

**Review by zubairabid — COMMENTED** [review]
Works. Removes the issue some people had running `npm install` on their machines.

@darthgera123 reports that `yarn install` works just fine without this fix. Either way, most of the team has done npm install so a useful one.

There remains a critical vulnerability that should be fixed, ideally inside this PR itself. Examining options there.

**Comment by yoogottamk** [comment]
For now pushed the vulnerability fix on this pr

From now on, I'll push directly on this repo itself

Tested after the changes. The website works as expected

**Review by zubairabid — APPROVED** [review]
Functional, no obvious issues.

**Pull request merged**
